default:
  # To be processed by Ellis lanes
  path_institution_raw:     "data-unshared/raw/institution.csv"
  path_variable_label_raw:  "data-public/metadata/variable-label.csv"

  path_ss_county:           "data-public/metadata/ss-county.csv"

  # Central Database (produced by Ellis lanes).
  # path_database:            "data-public/derived/db.sqlite3"

  # Derived Rectangles (produced by Ellis lanes).
  path_variable_label_derived:  "data-public/derived/variable-label.parquet"

  # Analysis-ready datasets (produced by scribes & consumed by analyses).
  path_institution_derived:     "data-unshared/derived/institution.parquet"


  # path_annotation:          "data-public/metadata/cqi-annotation.csv"

  path_log_flow:            !expr strftime(Sys.time(), "data-unshared/log/%Y/%Y-%m/flow-%Y-%m-%d--%H-%M-%S.log")

  # time_zone_local:          "America/Chicago"          # Force time calculations to be local, in case remotely run from another timezone.  See ?base::Sys.timezone()
